### ISSUE TITLE
Error occurred when using swift package manager

### ISSUE THREAD

**Issue by woosiki-prestolabs** [segment-integrations/analytics-swift-amplitude#10] opened 2023-07-27 22:32 UTC
I got a error when I add SegmentAmplitude in my swift package project.
Here is information and sample project.
- Test Project : [MyLibrary.zip](https://github.com/segment-integrations/analytics-swift-amplitude/files/12188623/MyLibrary.zip)
- package
```

let package = Package(
    ....
    dependencies: [
        .package(name: "Segment", url: "https://github.com/segmentio/analytics-swift.git", from: "1.4.7"),
        .package(name: "SegmentAmplitude", url: "https://github.com/segment-integrations/analytics-swift-amplitude.git", from: "1.2.0"),
        .package(name: "SegmentAppsFlyer", url: "https://github.com/segment-integrations/analytics-swift-appsflyer.git", from: "1.1.3"),
    .....
    ],
    .....
```
- command : swift build --package-path ./ --target MyLibrary --configuration debug --use-integrated-swift-driver
- error message
```
error: the library 'SegmentAmplitude' requires macos 10.13, but depends on the product 'Segment' which requires macos 10.15; consider changing the library 'SegmentAmplitude' to require macos 10.15 or later, or the product 'Segment' to require macos 10.13 or earlier.
error: the library 'SegmentAppsFlyer' requires macos 10.13, but depends on the product 'Segment' which requires macos 10.15; consider changing the library 'SegmentAppsFlyer' to require macos 10.15 or later, or the product 'Segment' to require macos 10.13 or earlier.
```

**Comment by skydivedan** [comment] 2023-09-12 16:03
You can't use `swift build` on this, or any other Segment integration. You need to build this with xcodebuild. I use `fastlane` to do this, which uses `xcodebuild`.

**Comment by alanjcharles** [comment] 2024-01-25 18:13
HI @woosiki-prestolabs i am going to close this out as I am unable to reproduce this. Please feel free to re-open if you have any additional information or reach out to `friends@segment.com` for a more thorough investigation. They can escalate any issues accordingly. Thanks!

**Closed by alanjcharles** 2024-01-25 18:13 UTC

**Comment by hoon-prestolabs** [comment] 2024-01-27 17:19
👀
